version: 0.2
phases:
  install:
    commands:
      - cd 01api
      - aws cloudformation package --template-file postman-newman-api.yaml
                                   --s3-bucket postman-newman
                                   --s3-prefix api-code
                                   --output-template-file postman-newman-api-output.yaml
artifacts:
  type: zip
  files:
    - 01api/postman-newman-api-output.yaml
