AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # simple function one
  FunctionOne:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function-one.handler
      Runtime: nodejs6.10
      CodeUri: ./
      FunctionName: FunctionOne
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /one
            Method: get
  FunctionTwo:
      Type: AWS::Serverless::Function
      Properties:
        Handler: function-two.handler
        Runtime: nodejs6.10
        CodeUri: ./
        FunctionName: FunctionTwo
        Events:
          GetResource:
            Type: Api
            Properties:
              Path: /two
              Method: get

Outputs:

    PostmanApi:
      Description: "Root API endpoint URL for Prod stage"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
      Export:
        Name: PostmanApiRoot