AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function-one.handler
      Runtime: nodejs6.10
      CodeUri: ./
      FunctionName: FunctionOne
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /one
            Method: get
  FunctionTwo:
      Type: AWS::Serverless::Function
      Properties:
        Handler: function-two.handler
        Runtime: nodejs6.10
        CodeUri: ./
        FunctionName: FunctionTwo
        Events:
          GetResource:
            Type: Api
            Properties:
              Path: /two
              Method: get
