AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaNewmanCodePipeLineFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: newman-pipeline.handler
      Runtime: nodejs6.10
      Timeout: 60
      FunctionName: PostmanCodePipelineTestRunner
